
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkvjdxxndapxpslovrlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrdmpkeHhuZGFweHBzbG92cmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzAxNzcsImV4cCI6MjA1NDI0NjE3N30.LntEpEZtnJ20ljHh_NKUUGK3yzivjEvFAGnFTa8DSV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: localStorage,
    },
  }
);

// Log de inicialização do cliente Supabase
console.log('Supabase client inicializado com configuração padrão');

// Função auxiliar para depuração de sessão
export const debugSession = async () => {
  const { data } = await supabase.auth.getSession();
  console.log('DEBUG SESSION:', data.session ? 'Sessão encontrada' : 'Sem sessão', 
    data.session ? {
      userId: data.session.user.id,
      expiresAt: new Date(data.session.expires_at! * 1000).toLocaleString()
    } : null
  );
  return data.session;
};
